# Generated by Django 4.1.1 on 2022-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('course', models.CharField(max_length=1, verbose_name='Курс')),
                ('description', models.TextField(verbose_name='Навыки')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('url_vk', models.URLField(blank=True, verbose_name='Ссылкa vk')),
                ('gmail', models.CharField(max_length=100, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('image', models.ImageField(upload_to='project/images/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('url', models.URLField(blank=True, verbose_name='Ссылкa')),
            ],
            options={
                'verbose_name': 'Награды',
                'verbose_name_plural': 'Награда',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.CharField(max_length=250, verbose_name='Описания проекта')),
                ('image', models.ImageField(upload_to='project/images/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Ссылкa')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_title', models.CharField(max_length=100, verbose_name='Имя Фамилия')),
                ('team_image', models.ImageField(upload_to='project/images/', verbose_name='Изображение')),
                ('team_description', models.CharField(max_length=50, verbose_name='HardSkills')),
                ('team_url_github', models.URLField(blank=True, verbose_name='Ссылкa github')),
                ('team_url_telegram', models.URLField(blank=True, verbose_name='Ссылкa telegram')),
                ('team_url_vk', models.URLField(blank=True, verbose_name='Ссылкa vk')),
            ],
            options={
                'verbose_name': 'Человека',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
